mkdir ELEMENTtest
copy BinhlEmul\bin\Debug\*.exe ELEMENTtest\
copy BinhlEmul\bin\Debug\*.dll ELEMENTtest\
copy Templates\TestsV2\*.emu ELEMENTtest\
copy Templates\V2\*.binhl ELEMENTtest\
del ELEMENTtest\*.vshost.exe
cd ELEMENTtest
BinhlEmul.exe AND.emu
BinhlEmul.exe OR.emu
BinhlEmul.exe NOT.emu
BinhlEmul.exe GND.emu
BinhlEmul.exe TRIG_D.emu
BinhlEmul.exe VCC.emu
BinhlEmul.exe DUP2.emu
BinhlEmul.exe DUP3.emu
BinhlEmul.exe DUP4.emu
BinhlEmul.exe DUP5.emu
BinhlEmul.exe DUP6.emu
BinhlEmul.exe DUP7.emu
BinhlEmul.exe DUP8.emu
BinhlEmul.exe DUP9.emu
BinhlEmul.exe DUP10.emu
BinhlEmul.exe DUP11.emu
BinhlEmul.exe DUP12.emu
BinhlEmul.exe DUP13.emu
BinhlEmul.exe DUP14.emu
BinhlEmul.exe DUP15.emu
BinhlEmul.exe DUP16.emu
BinhlEmul.exe DUP17.emu
BinhlEmul.exe DUP18.emu
BinhlEmul.exe DUP19.emu
BinhlEmul.exe DUP20.emu
BinhlEmul.exe DUP21.emu
BinhlEmul.exe DUP22.emu
BinhlEmul.exe DUP23.emu
BinhlEmul.exe AND2.emu
BinhlEmul.exe AND3.emu
BinhlEmul.exe AND4.emu
BinhlEmul.exe AND5.emu
BinhlEmul.exe AND6.emu
BinhlEmul.exe AND7.emu
BinhlEmul.exe AND8.emu
BinhlEmul.exe OR2.emu
BinhlEmul.exe OR3.emu
BinhlEmul.exe OR4.emu
BinhlEmul.exe OR5.emu
BinhlEmul.exe OR6.emu
BinhlEmul.exe OR7.emu
BinhlEmul.exe OR8.emu